baseURL = "http://thefacelesspanda.netlify.com"
languageCode = "en-us"
title = "The Faceless Panda"
theme = "ananke"
pygmentsCodefences = true
enableEmoji = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableRobotsTXT = true
sectionPagesMenu = "main"

[params]
  favicon = "images/icon_32.png"
  description = "I am a panda without a face."
  twitter = "https://twitter.com/Oddwel"
  instagram = "https://www.instagram.com/thefacelesspanda"
  youtube = "https://www.youtube.com/channel/UCBufNbImQigWwDBJ66gvXPA"
  github = "https://github.com/facelesspanda"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/panda_banner.jpg"