---
title: "Hello World"
date: 2018-09-01T07:59:42+02:00
draft: false
---
* A new beginning
I had previously established a blog over at [[http://facelesspanda.github.io][Github Pages]], and it was fine.

I didn't use it much, though. And lately I've started wanting to blog again.

But in the meanwhile I drastically changed my way to edit and write code and text.
I used to [[https://facelesspanda.github.io/2016-10-02-my-atom-setup/][work under Atom]], but now I heavily rely on [[http://spacemacs.org/][Spacemacs]] and [[https://code.visualstudio.com/][Visual Studio Code]].
Also I'm writing in [[https://orgmode.org/][org-mode]] now, which feels much better than limiting myself to markdown.

** So is this gonna be mostly empty like the other one?
Probably, to be honest.

I /am/ working on an adventure game, that I call */The Collapse/*,
and I frequently post youtube videos that show my progress.

What I /might/ end up doing is using this blog to go into more detail about how things are working out.
What I /might/ end up doing instead is using my travel time to and from uni to
vlog about the development of things.

What I /may/ end up doing is just not do much more than what I'm already doing,
and stay focused on my university work for most of the time.

** So what's the point of this post?
Without lying, it's mostly because I can't deploy the site without a post, or a page.

But I could have just have a post saying /"initial commit"/ or something,
that would have been somewhat funny.

Instead I went on an unorganized ramble about unorganized thoughts.
And I think it's fitting for a first post, as it really represents
what the whole blog is going to be :

#+BEGIN_QUOTE
A HUGE MESS
#+END_QUOTE
